config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	get '/main' => 'main_ui#main_ui'
	get '/interview' => 'interview_ui#interview'
	get '/schedule' => 'interview_ui#schedule'
	get '/applicant' => 'interview_ui#applicant'
	get '/questions' => 'interview_ui#questions'
	get '/information' => 'interview_ui#information'
	get '/link' => 'interview_ui#link'
	get '/style' => 'interview_ui#style'
	get '/mypage' => 'interview_ui#mypage'
	get '/questions/read' => 'interview_ui#questions_read'
	get '/applicant/read' => 'interview_ui#applicant_read'
	get '/schedule/read' => 'interview_ui#schedule_read'
	get '/schedule/check' => 'interview_ui#schedule_is_exist'
	# get '/information/modal' => 'interview_ui#renderText'
	post '/applicant/create' => 'interview_ui#applicant_create'
	post '/schedule/create' => 'interview_ui#schedule_create'
	post '/style/search' => 'interview_ui#searchLocation'
	patch '/schedule/patch' => 'interview_ui#schedule_patch'
	delete '/applicant/destroy' => 'interview_ui#applicant_destroy'
	authenticated :user do
		root 'interview_ui#interview', as: :authenticated_root
	end
	root 'main_ui#main_ui'
end

app/controllers/interview_ui_controller.rb
require 'open-uri'
require 'json'
require "net/https"
require "uri"
require 'faraday'

class InterviewUiController < ApplicationController
	before_action :authenticate_user!
	def interview
		pageId = params[:page]
		videoId = params[:'video-analytics']
		if pageId == '1'
			render "interview.html.erb"
		end
		if videoId == '1'
			render "video_1.html.erb"
		elsif videoId == '2'
			render "video_2.html.erb"
		end
	end
	
	def schedule
	end
	
	def applicant
		@find = IsPassed.where(:user_id => current_user.id)
	end
	
	def questions
		@list = QuestionsList.order("RANDOM()").first(5)
	end
	
	def information
		pageId = params[:page]
		if pageId == '1'
			render "information.html.erb"
		elsif pageId == '2'
			render "information_2.html.erb"
		end
	end
	
	def link
	end
	
	def style
	end
	
	def mypage
	end
	
	def searchLocation
		cID = ENV["Naver_Search_Client_ID"]
    cSecret = ENV["Naver_Search_Client_Secret"]
		sWord = params[:query].to_s
		res = Faraday.get do |req|
			req.url "https://openapi.naver.com/v1/search/local.json?query=#{sWord}&display=10&start=1"
			req.headers = { 'Host' => 'openapi.naver.com',
											'User-Agent' => 'curl/7.49.1',
											'Accept' => '*/*',
											'X-Naver-Client-Id' => cID,
											'X-Naver-Client-Secret' => cSecret }
    end
		resBody = JSON.parse(res.body)
		render :json => resBody['items']
	end
	# def renderText
	# 	modalId = params[:id]
	# 	data = File.read("#{Rails.root}/app/views/interview_ui/info2_modal#{modalId}.txt")
	# 	render :text => data
	# end
	
	def questions_read
		list = QuestionsList.order("RANDOM()").first(5)
		render :json => list, :status => 200
	end
	
	def applicant_create
		if params[:applicantId] == ''
			write = IsPassed.new
		else
			write = IsPassed.find(params[:applicantId]);
		end
		write.user_id = current_user.id
		write.company_name = params[:company_name]
		write.work_name = params[:work_name]
		write.deadline = params[:deadline]
		write.site_name = params[:site_name]
		write.deadline = params[:deadline]
		write.passed = params[:passed]
		write.startdate = params[:startdate]
		write.company_site = params[:company_site]
		write.save
		redirect_to :back
	end
	
	def applicant_read
		read = IsPassed.where(:id => params[:id])
		render :json => read, :status => 200
	end
	
	def applicant_destroy
		read = IsPassed.find_by(:id => params[:id])
		if read.user_id == current_user.id
			if read.destroy!
				render :json => "true", :status => 200
			else
				render :json => "false", :status => 200
			end
		else
			render :json => "false", :status => 200
		end
	end
	
	def schedule_create
		write = Schedule.new
		write.user_id = current_user.id
		write.date = params[:picked]
		write.title = params[:title]
		write.content = params[:content]
		write.save
		redirect_to :back
	end
	
	def schedule_patch
		write = Schedule.find_by(:user_id => current_user.id, :date => params[:picked])
		write.update({:title => params[:title], :content => params[:content]})
		redirect_to :back
	end
	
	def schedule_read
		find = Schedule.where(:user_id => current_user.id, :date => params[:fulldate])
		render :json => find, :status => 200
	end
	
	def schedule_is_exist
		find = Schedule.exists?(:user_id => current_user.id, :date => params[:fulldate])
		if find
			render :json => "true", :status => 200
		else
			render :json => "false", :status => 200
		end
	end
end

app/helpers/interview_ui_helper.rb
module InterviewUiHelper
end

app/views/interview_ui/applicant.html.erb
<style>
	.modal.modal-fixed-footer .modal-content {
		position: relative;
	}
	
	.dropdown-content li > a, .dropdown-content li > span {
		color: #607d8b;
	}
	
	tbody > tr {
		cursor: pointer;
	}
	
	.hvr-icon-fade:hover .hvr-icon, .hvr-icon-fade:focus .hvr-icon, .hvr-icon-fade:active .hvr-icon {
		color: #ef5350;
	}
</style>
<script>
	$(document).ready(function(){
		$('.modal').modal();
		$('.datepicker').datepicker();
		$('select').formSelect();
		var q = document.querySelectorAll('tbody > tr');
		for (var i = 0; i < q.length; i++) q[i].addEventListener('click', editApplicant);
		var r = document.getElementsByClassName('remove-list');
		for (var i = 0; i < r.length; i++) r[i].addEventListener('click', removeList);
	});
	
	function removeList(sender) {
    sender.stopPropagation();
		swal({
			title: '정말 일정을 삭제하시겠습니까?',
			text: "해당 작업은 되돌릴 수 없습니다.",
			type: 'question',
			showCancelButton: true,
			confirmButtonColor: '#3085d6',
			cancelButtonColor: '#d33',
			confirmButtonText: '삭제',
			cancelButtonText: '취소'
		}).then((result) => {
			if (result.value) {
				var applicantId = sender.target.parentNode.parentNode.getAttribute('id');
				applicantId = applicantId.slice(5);
				fetch("/applicant/destroy?id=" + applicantId, {
					method: "DELETE",
					dataType : 'json'
				}).then(function(response) {
					if (response.ok) {
						var rList = document.querySelector('tr#list-' + applicantId);
						rList.remove();
						response.json().then(function(data) {
							swal({
								title: '삭제되었습니다!',
								text: '해당 일정이 성공적으로 삭제되었습니다.',
								type: 'success',
								confirmButtonText: '확인'
							});
						});
					}
				}, function(e) {
					swal({
						title: ':(',
						text: '해당 일정을 삭제하던 도중 오류가 발생하였습니다.',
						type: 'error',
						confirmButtonText: '확인'
					});
				});
			}
		})
	}
	
	function editApplicant(sender) {
		if (sender) {
			var applicantId = sender.target.parentNode.getAttribute('id');
			applicantId = applicantId.slice(5);
			fetch("/applicant/read?id=" + applicantId, {
				method: "GET",
				dataType : 'json'
			}).then(function(response) {
				if (response.ok) {
					$('#applicantId').val(applicantId);
					response.json().then(function(data) {
						$('#company_name').val(data[0].company_name);
						$('#work_name').val(data[0].work_name);
						$('#deadline').val(data[0].deadline);
						document.getElementById("site_name").value = data[0].site_name;
						$('.input-field.dropdown-field input[class*="select-dropdown"]').eq(0).val(data[0].site_name);
						document.getElementById("passed").value = data[0].passed;
						$('.input-field.dropdown-field input[class*="select-dropdown"]').eq(1).val(data[0].passed);
						$('#startdate').val(data[0].startdate);
						$('#company_site').val(data[0].company_site);
					});
					$('#modal1').modal('open');
				}
			}, function(e) {
				alert("알 수 없는 에러가 발생하였습니다. 상태가 지속된다면 관리자에게 문의하세요!");
			});
		}
		else {
			$('#applicantId').val('');
			$('#company_name').val('');
			$('#work_name').val('');
			$('#deadline').val('');
			$('.input-field.dropdown-field input[class*="select-dropdown"]')[0].value = '접수한 사이트를 선택해주세요.';
			$('.input-field.dropdown-field input[class*="select-dropdown"]')[1].value = '진행 상황을 선택해주세요.';
			$('#startdate').val('');
			$('#company_site').val('');
			$('#modal1').modal('open');
		}
	}
</script>
<!-- Modal Structure -->
<%= form_tag(applicant_create_path, method: "POST") do %>
	<div id="modal1" class="modal modal-fixed-footer" style="width: 50vw">
		<%= hidden_field_tag 'applicantId', ''  %>
		<div class="modal-content">
			<h5>현황 작성 및 수정</h5><br>
			<div class="row">
				<div class="input-field col s4">
					<input placeholder="지원한 회사명을 작성해주세요." id="company_name" name="company_name" type="text" class="validate">
					<label class="active" for="company_name">회사명</label>
				</div>
				<div class="input-field col s4">
					<input placeholder="지원한 직무명을 작성해주세요." id="work_name" name="work_name" type="text" class="validate">
					<label class="active" for="company_name">지원직무</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s8">
					<input placeholder="지원 마감일을 선택해주세요." type="text" id="deadline" name="deadline" class="datepicker">
					<label class="active" for="deadline">지원 마감일자</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s4 dropdown-field">
					<select id="site_name" name="site_name">
						<option value="" disabled selected>접수한 사이트를 선택해주세요.</option>
						<option value="공식 홈페이지">공식 홈페이지</option>
						<option value="사람인">사람인</option>
						<option value="잡코리아">잡코리아</option>
						<option value="인크루트">인크루트</option>
						<option value="자소설닷컴">자소설닷컴</option>
						<option value="잡플래닛">잡플래닛</option>
					</select>
					<label>접수처</label>
				</div>
				<div class="input-field col s4 dropdown-field">
					<select id="passed" name="passed">
						<option value="" disabled selected>진행 상황을 선택해주세요.</option>
						<option value="합격">합격</option>
						<option value="불합격">불합격</option>
						<option value="평가중">평가중</option>
					</select>
					<label>합·불 여부</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s8">
					<input placeholder="서류 발표 시작일을 선택해주세요." type="text" id="startdate" name="startdate" class="datepicker">
					<label class="active" for="startdate">서류발표 기간</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s8">
					<input placeholder="지원한 회사의 채용 사이트를 기록해주세요." id="company_site" name="company_site" type="text" class="validate">
					<label class="active" for="company_site">채용 사이트</label>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<button type="button" class="modal-close waves-effect btn-flat">취소</button>
			<%= button_tag(:type => "submit", :class => "modal-close waves-effect btn-flat") do %>작성<% end %>
		</div>
	</div>
<% end %>
<div class="category" style="margin: 6vh 0;">
<h5><i class="small material-icons" style="vertical-align: text-top;">dashboard</i>&ensp;입사 지원 현황</h5>
</div>
<div class="addApplication hvr-icon-buzz-out" style="float: right;"><i class="small material-icons hvr-icon" style="color:#607d8b; cursor: pointer;" onclick="editApplicant(false)">playlist_add</i></div>
<div class="questions-list" style="font-size: large; margin-top: 2vh;">
	<table class="highlight centered">
		<thead>
			<tr>
					<th></th>
					<th>회사명</th>
					<th>지원직무</th>
					<th>지원 마감일자</th>
					<th>접수처</th>
					<th>합·불 여부</th>
					<th>서류발표 기간</th>
					<th>채용 사이트</th>
			</tr>
		</thead>
		<tbody class="animated fadeIn">
			<% @find.reverse.each do |f| %>
			<% if f.passed == "합격" %>
			<tr id="list-<%= f.id %>" style="color: green">
			<% elsif f.passed == "불합격" %>
			<tr id="list-<%= f.id %>" style="color: red">
			<% else %>
			<tr id="list-<%= f.id %>">
			<% end %>
				<td class="remove-list hvr-icon-fade" style="color: #757575; font-size: 5px; margin-left: 40%"><i class="material-icons hvr-icon" style="vertical-align: text-top">highlight_off</i></td>
				<td><%= f.company_name %></td>
				<td><%= f.work_name %></td>
				<td><%= f.deadline %></td>
				<td><%= f.site_name %></td>
				<td><%= f.passed %></td>
				<td><%= f.startdate %></td>
				<td style="color: #039be5;"><%= f.company_site %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/interview_ui/information.html.erb
<style>
	.pagination li.active {
		background-color: #607d8b;
	}
</style>
<div class="category" style="margin: 6vh 0;">
<h5><i class="small material-icons" style="vertical-align: text-top;">speaker_notes</i>&ensp;인사 담당자가 말한다!</h5>
</div>
<ul class="pagination" style="text-align: right">
    <li class="disabled"><a href="javascript:void();"><i class="material-icons">chevron_left</i></a></li>
    <li class="active waves-effect"><a href="?page=1">1</a></li>
    <li class="waves-effect"><a href="?page=2">2</a></li>
    <li class="disabled waves-effect"><a href="javascript:void();">3</a></li>
    <li class="disabled waves-effect"><a href="javascript:void();">4</a></li>
    <li class="disabled"><a href="javascript:void();"><i class="material-icons">chevron_right</i></a></li>
</ul>
<br>
<div class="row">
	<div class="col s12 m12 l5">
		<iframe width="426" height="240" src="https://www.youtube-nocookie.com/embed/i0CWefibb9g?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
	</div>
	<div class="col s12 m12 l7">
		<h5>
			2018 채용 트렌드 주요 이슈&emsp;<a href="https://www.jobkorea.co.kr/net/starter/tip/View?Inside_No=13948" target="_blank"><i class="material-icons">insert_link</i></a>
		</h5>
		<br>
		<ol style="font-size: larger">
			<li>2018년, 공공기관 채용 사상 최대치!</li>
			<li>채용 인원 가장 많은 곳은? 한국철도공사, 한국전력공사 순...</li>
			<li>공무원 신규채용 규모 늘고, 금융 공공기관 명예퇴직 활성화!</li>
		</ol>
	</div>
</div>
<br>
<div class="row">
	<div class="col s12 m12 l5">
		<iframe width="426" height="240" src="https://www.youtube-nocookie.com/embed/3iCAiA9Ls5g?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
	</div>
	<div class="col s12 m12 l7">
		<h5>
			인사담당자가 말하는 AhnLab 채용 주요 이슈&emsp;<a href="http://job.incruit.com/entry/openempcoreview_popup.asp?comp=C852E1EF86F2B9937A5B8DCF8176AA4EEA4663193D2D2213F094EEE7AC8FAEEB" target="_blank"><i class="material-icons">insert_link</i></a>
		</h5>
		<br>
		<ol style="font-size: larger">
			<li>주요서비스 : 엔드 포인트 보안 / 네트워크 보안 / 온라인 보안 / 온라인 게임 보안 / 유틸리티 / 정보보호컨설팅 / 보안관제 / 보안 포털</li>
			<li>인재상 : 인성 / 전문성 / 팀워크</li>
			<li>비전 : 우리는 끊임없는 연구개발로 함께 살아가는 사회에 기여한다.</li>
		</ol>
	</div>
</div>
<br>
<div class="row">
	<div class="col s12 m12 l5">
		<iframe width="426" height="240" src="https://www.youtube-nocookie.com/embed/q0jUVB2XlaM?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
	</div>
	<div class="col s12 m12 l7">
		<h5>
			인사담당자가 말하는 NHN엔터테인먼트 채용 주요 이슈&emsp;<a href="http://job.incruit.com/entry/openempcoreview_popup.asp?comp=71E2AA7F2F7B5CD49C5E336708BD39DE1173C1FF18737018D519DA996CB09F11" target="_blank"><i class="material-icons">insert_link</i></a>
		</h5>
		<br>
		<ol style="font-size: larger">
			<li>주요서비스 : 결제 / 게임 / 쇼핑 / 문화생활 / IT솔루션</li>
			<li>인재상 : 변화에 민감하고 빠르게 대응하며 즐길 줄 아는 사람</li>
			<li>비전 : 즐거움으로 연결된 모든 가치를 이야기합니다.</li>
		</ol>
	</div>
</div>
<br>

app/views/interview_ui/mypage.html.erb
<div class="category" style="margin-top: 6vh;">
<h5><i class="small material-icons" style="vertical-align: text-top;">account_circle</i>&ensp;마이페이지</h5>
</div>
<div class="profile-content" style="font-size: large; margin-top: 5vh;">
	<table class="highlight centered">
		<tbody>
			<tr>
				<td class="bold">이름</td>
				<td><%= current_user.name %></td>
			</tr>
			<tr>
				<td class="bold">이메일</td>
				<td><%= current_user.email %></td>
			</tr>
			<tr>
				<td class="bold">연락처</td>
				<td><%= current_user.pnumber %></td>
			</tr>
			<tr>
				<td class="bold">출신학교</td>
				<td><%= current_user.graduate %></td>
			</tr>
			<tr>
				<td class="bold">관심분야</td>
				<td><%= current_user.interest %></td>
			</tr>
			<tr>
				<td class="bold">희망하는 회사</td>
				<td><%= current_user.hope_company %></td>
			<tr>
				<td class="bold">희망하는 직무</td>
				<td><%= current_user.hope_work %></td>
			</tr>
			<tr>
				<td class="bold">한 마디 각오</td>
				<td><%= current_user.fighting %></td>
			</tr>
		</tbody>
	</table>
</div>

app/views/interview_ui/schedule.html.erb
<style>
	.loader {
		display: block;
		z-index: 999;
		position: absolute;
		background-color: rgba(0,0,0,0.5);
		text-align: center;
		visibility: hidden;
	}
	
	.preloader-wrapper {
		top: 50%;
	}
</style>
<script>
	$(document).ready(function(){
		$('.modal').modal();
		vanillaCalendar.month = document.querySelectorAll('[data-calendar-area="month"]')[0];
		vanillaCalendar.next = document.querySelectorAll('[data-calendar-toggle="next"]')[0];
		vanillaCalendar.previous = document.querySelectorAll('[data-calendar-toggle="previous"]')[0];
		vanillaCalendar.label = document.querySelectorAll('[data-calendar-label="month"]')[0];
		vanillaCalendar.init();
	});
</script>
<!-- Create Modal Structure -->
<%= form_tag(schedule_create_path, method: "POST") do %>
  <div id="createModal" class="modal modal-fixed-footer">
		<input type="hidden" name="picked" data-calendar-label="picked"></input>
    <div class="modal-content">
			<h5><span class="selected-date"></span>&nbsp;일정</h5><br>
			<div class="row">
					<form class="col s12">
							<div class="row">
									<div class="input-field col s12">
											<%= text_field_tag("title", nil, {:id => "input_text", :required => true, :autofocus => true}) %>
											<%= label_tag(nil, "제목", {:for => "input_text"}) %>
									</div>
									<div class="input-field col s12">
											<%= text_area_tag("content", nil, {:id => "textarea_content", :class => "materialize-textarea", :required => true}) %>
											<%= label_tag(nil, "내용", {:for => "textarea_content"}) %>
									</div>
							</div>
					</form>
			</div>
    </div>
    <div class="modal-footer input_shown">
			<button type="button" class="modal-close waves-effect btn-flat">취소</button>
			<%= button_tag(:type => "submit", :class => "modal-close waves-effect btn-flat") do %>등록<% end %>
    </div>
  </div>
<% end %>
<!-- Patch Modal Structure -->
<%= form_tag(schedule_patch_path, method: "PATCH") do %>
  <div id="patchModal" class="modal modal-fixed-footer">
		<input type="hidden" name="picked" data-calendar-label="picked"></input>
    <div class="modal-content">
			<h5><span class="selected-date"></span>&nbsp;일정</h5><br>
			<div class="row">
					<form class="col s12">
							<div class="row">
									<div class="input-field col s12">
											<%= text_field_tag("title", nil, {:id => "input_text", :required => true, :autofocus => true}) %>
											<%= label_tag(nil, "제목", {:for => "input_text"}) %>
									</div>
									<div class="input-field col s12">
											<%= text_area_tag("content", nil, {:id => "textarea_content", :class => "materialize-textarea", :required => true}) %>
											<%= label_tag(nil, "내용", {:for => "textarea_content"}) %>
									</div>
							</div>
					</form>
			</div>
    </div>
    <div class="modal-footer input_shown">
			<button type="button" class="modal-close waves-effect btn-flat">취소</button>
			<%= button_tag(:type => "submit", :class => "modal-close waves-effect btn-flat") do %>등록<% end %>
    </div>
  </div>
<% end %>
<div class="category" style="margin: 6vh 0;">
<h5><i class="small material-icons" style="vertical-align: text-top;">today</i>&ensp;일정 관리</h5>
</div>
<div class="row">
	<div class="col s12 m8 offset-m2 xl6 offset-xl3">
		<div id="v-cal">
			<div class="vcal-header">
				<button type="button" class="vcal-btn" data-calendar-toggle="previous">
					<svg height="24" version="1.1" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
						<path d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"></path>
					</svg>
				</button>

				<div class="vcal-header__label" data-calendar-label="month"></div>

				<button type="button" class="vcal-btn" data-calendar-toggle="next">
					<svg height="24" version="1.1" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
						<path d="M4,11V13H16L10.5,18.5L11.92,19.92L19.84,12L11.92,4.08L10.5,5.5L16,11H4Z"></path>
					</svg>
				</button>
			</div>

			<div class="vcal-week">
				<span>Mon</span> <span>Tue</span><span>Wed</span> <span>Thu</span> <span>Fri</span> <span>Sat</span> <span>Sun</span>
			</div>
			<div class="vcal-body" data-calendar-area="month"></div>
		</div>
	</div>
</div>